import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryClientProviderClient from "@/components/providers/query-client";
import I18nProvider from "@/components/providers/i18n";
import ThemeProvider from "@/components/providers/theme";
import RTLProvider from "@/components/ui/rtl-provider";
import Header from "@/components/ui/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryClientProviderClient>
          <ThemeProvider>
            <I18nProvider>
              <RTLProvider />
              <Header />
              {children}
            </I18nProvider>
          </ThemeProvider>
        </QueryClientProviderClient>
      </body>
    </html>
  );
}
